services:
  - type: web
    name: wrectifai-api
    runtime: node
    plan: free
    buildCommand: npm install && npx nx build api
    startCommand: node dist/api/main.js
    envVars:
      - key: NODE_VERSION
        value: 22.11.0
